name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Ejercicios Básicos
      id: test-ejercicios-basicos
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 100
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-EJERCICIOS-BASICOS_RESULTS: "${{steps.test-ejercicios-basicos.outputs.result}}"
      with:
        runners: test-ejercicios-basicos
